import type { Metadata } from "next";
import "./globals.css";
import Layout from "./components/Layout";
import CartPageContextProvider from "./components/context/CartPageContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>

          <CartPageContextProvider>
            <Layout>
              {children}
            </Layout>
          </CartPageContextProvider>
      </body>
    </html>
  );
}
