import type { Metadata } from "next";
import "./globals.css";
import Layout from "./components/Layout";
import CartPageContextProvider from "./components/context/CartPageContext";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="fa" dir="rtl">
        <body>
            <CartPageContextProvider>
              <Layout>
                {children}
              </Layout>
            </CartPageContextProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
